### ISSUE TITLE
Add stop/pause (delay) when shutter direction is changed due to new level request

### ISSUE THREAD

**Issue by kluszczyn** [marvinroger/arduino-shutters#1]
When shutter is moving and new level is requested shutter should pause for predefined time before changing direction. This will prevent switching electrical motor direction in very short time and will help keep electrical relays in good condition.

When new level request is not changing shutter direction then shutter should not stop due to new level request - no halt() should be called.

**Comment by marvinroger** [comment]
I've fixed the last point, halt is not called when the direction is the same. However for the first point, I'll need to refactor before doing it in a clean way. You can add a `delay()` in your callbacks, this is what I did when I worked with relays.

**Comment by parachutesj** [comment]
Hi,
Do you have any particular hardware requirements for it to work?
I use a Nano with relays and after implementing my code for up, down, halt it works but never got requestLevel working.

Regards,
SJ

**Comment by marvinroger** [comment]
Have you take a look at the [example code](https://github.com/marvinroger/arduino-shutters/blob/master/examples/BasicShutters/BasicShutters.ino)?

**Comment by lucaswalker** [comment]
Hi, it's the same for me.
RequestLevel is not working.
It tried the version commited Nov 7, 2015 and it work perfectly for me.
Regards,
Lucas

**Comment by marvinroger** [comment]
Looks like I broke something... I'll fix when I have more time. :)

**Comment by fab33** [comment]
I think I find the bug ! it's here (L112) : 
`if (this->_moving && direction == this->_direction) {
    this->_targetLevel = level;
  } else {
    this->_stopNeeded = STOP_NEW_LEVEL;
    this->_requestLevel = level;
`
I Change to STOP_NEW_LEVEL to STOP_NONE and it works fine.
I will report another issue.

**Comment by marvinroger** [comment]
Done! I just released the v2.0.0 which add a safety delay between `up`, `halt` and `down` callbacks.
