### ISSUE TITLE
courseTimeDown < courseTimeUp

### ISSUE THREAD

**Issue by ludodoucet** [marvinroger/arduino-shutters#11]
Hello, I have a small question:
The closure is faster than opening within 4 seconds.
Is it possible to consider two race times in a future version?

**Comment by marvinroger** [comment]
It is. 🙂

**Comment by marvinroger** [comment]
Released as beta: https://github.com/marvinroger/arduino-shutters/releases/tag/v3.0.0-beta.1

Please fill an issue if there's something not working. 😉

**Comment by ludodoucet** [comment]
J'ai juste copier le répertoire src vers le dossier de la bibliothèque.
J'ai des erreurs dans la compilation, peut être du à des changements dans l'API.
...Je rame

**Comment by ludodoucet** [comment]
`src/Railduino_4Volets.cpp:152:155: error: no matching function for call to 'Shutters::Shutters(const long unsigned int&, void (&)(), void (&)(), void (&)(), uint8_t (&)(), void (&)(uint8_t), const float&, void (&)(uint8_t))'
Shutters shutters1(courseTime1, shutters1Up, shutters1Down, shutters1Halt, shutters1GetState, shutters1SetState, calibrationRatio, onshutters1LevelReached);
^
src/Railduino_4Volets.cpp:152:155: note: candidates are:
In file included from lib/Shutters/Shutters.h:4:0,
from src/Railduino_4Volets.cpp:4:
lib/Shutters/Shutters.hpp:68:3: note: Shutters::Shutters(ShuttersInternal::OperationFunction, ShuttersInternal::OperationFunction, ShuttersInternal::OperationFunction, ShuttersInternal::GetStateFunction, ShuttersInternal::SetStateFunction)
Shutters(ShuttersInternal::OperationFunction up, ShuttersInternal::OperationFunction down, ShuttersInternal::OperationFunction halt, ShuttersInternal::GetStateFunction getState, ShuttersInternal::SetStateFunction setState);
^
lib/Shutters/Shutters.hpp:68:3: note:   candidate expects 5 arguments, 8 provided
lib/Shutters/Shutters.hpp:28:7: note: constexpr Shutters::Shutters(const Shutters&)
class Shutters {
^
lib/Shutters/Shutters.hpp:28:7: note:   candidate expects 1 argument, 8 provided
lib/Shutters/Shutters.hpp:28:7: note: constexpr Shutters::Shutters(Shutters&&)
lib/Shutters/Shutters.hpp:28:7: note:   candidate expects 1 argument, 8 provided`

**Comment by ludodoucet** [comment]
Il y a beaucoup de changement dans le fichier exemple, je vais essayer de m'en inspirer
