### ISSUE TITLE
Manually control UP and DOWN

### ISSUE THREAD

**Issue by tcmoreno** [marvinroger/arduino-shutters#15]
Hi, thanks for this awesome library, I'm starting to play with it.

Is there any way to manually control de UP and DOWN movements from a button? I would like to have both options:

- Set a desire % level from an app.
- Manually push a button to control the shutters. In this case I would like to track the level.

I have tried to use the shutters._up() function by making it public, but no luck at all.
Thanks

**Comment by marvinroger** [comment]
Hi!

Make your up button go to 0% and your down button go to 100%, it will do
the job. :)

**Comment by tcmoreno** [comment]
Not sure if I get it...
Let imagine I set the level using Home Assistant to 75%.
Then, I manually push a button in the wall to move it down. The shutter will go down until I release the button, in example it will stop at 85%.

The point is that when using buttons you may stop at any point between 0% and 100%, and I would like to track the position as well.

**Comment by marvinroger** [comment]
Alright. When you push the button to go up, set the level to 0%. That way,
the shutters will go up. When you push the button to go down, set the level
to 100%, so it goes down.

The point is, whenever you release the up or down button, just call the
‘stop’ function. If the shutters are going down and we’re for example at
80.5%, it will automatically stop at 81%. And you’ll have the wanted
behavior.

**Comment by tcmoreno** [comment]
Sounds good, I will try and confirm if works.
Thanks

**Comment by tcmoreno** [comment]
Got it working! I will try to roll out now to a real deployment and see how it works in daily use. Thanks

**Comment by marvinroger** [comment]
Perfect! Feel free to reopen an issue if you encouter a bug.
