### ISSUE TITLE
Calibration obligatoire??

### ISSUE THREAD

**Issue by marmoul70** [marvinroger/arduino-shutters#16]
Bonjour Marvin,

Bravo pour votre project qui est  vraiment cool et correspond à mon besoin.

J'ai une question/demande car je rencontre un léger problème.
En effet j'ai des reboot aléatoire de module surement du à mon installation électrique. 
Le problème est que lors du reboot les volets se calibre... Imaginez ma femme à se moment la :)
J'aimerai savoir si il était possible de se passer de la calibration quand le module est déja en place. 
En effet, la position du volet est stockée dans l'epromm il me semble. On pourrais imaginer que si la valeur de l'epromm est nul ( du à nouvelle installation) calibration sinon pas de calibration...

Pensez-vous que cela sois réalisable?

Merci d'avance.

Marmoul

**Comment by marvinroger** [comment]
Salut !

Bienvenue sur GitHub. 😉 De façon générale, le tutoiement est de mise ici.
Le volet ne se recalibre pas si effectivement les données sont stockées dans EEPROM. Mais est-ce que tu as géré le stockage et la récupération des valeurs dans ton code ? (voir https://github.com/marvinroger/arduino-shutters/blob/master/examples/BasicShutters/BasicShutters.ino)

**Comment by marmoul70** [comment]
Effectivement je débute sur Github merci des précisions :)
La modif du code n'est pas entièrement de moi j'ai repris pour adapter à mon besoin.
c'est un projet sur jeedom avec ajout d'autre lib comme wifimanager et mqtt
j'ai regardé et tous semble correct je suis vraiment pas un crack avec arduino 

Je te met le fichier .ino si jamais 

merci

[Esp_ch1.ino.zip](https://github.com/marvinroger/arduino-shutters/files/1711346/Esp_ch1.ino.zip)

**Comment by marmoul70** [comment]
Salut Marvin,
je reviens vers toi concernant mon problème. J'ai pas mal chercher ce week-end et je pense avoir trouvé.
En effet j'ai recompiler mon code avec un autre ide arduino (c'est la 2eme fois que mon compilateur me joue des tours) et sa fonctionne. Je confirme que une fois le level inscrit dans l'eeprom plus de mouvement aléatoire lors du reboot.
J'ai également ajouté la fonction reset pour vider l'eeprom ( je ne sais pas si sa a joué mais le résultat est la).
Merci cette lib est au top.
A bientot

Marmoul

Edit je pense avoir trouvé un bug j'ai ouvert une nouvelle issue :)

**Comment by marvinroger** [comment]
@marmoul70 parfait ! Merci 😉
