### ISSUE TITLE
Bug EEPROM = 100

### ISSUE THREAD

**Issue by marmoul70** [marvinroger/arduino-shutters#17]
Salut Marvin,
J'ouvre une nouvelle issue car j'ai trouver un bug dans la lib.

En effet j'ai remarqué que:
Si level = 100 et que mon volet reboot la lib lance la calibration.
Si level =< 99 et que le volet reboot la lib ne lance pas la calibration et tout fonctionne normalement,

N'y aurait-il pas un bug dans le stockage de la valeur 100 dans l'eeprom?

Marmoul

Edit: J'ai remplacer le level 100 par 99 dans mon code et sa fonctionne bien maintenant.
Le problème serait que chez moi?

**Comment by marvinroger** [comment]
Je vais vérifier ça, merci pour l'info !

**Comment by marvinroger** [comment]
Tu peux essayer de changer la ligne https://github.com/marvinroger/arduino-shutters/blob/master/src/Shutters/StoredState.hpp#L6 par 

```c++
const uint8_t LEVEL_OFFSET = 27;
```

Et me dire si ça fonctionne ?

**Comment by marmoul70** [comment]
Salut. 
Désolé du retard. Je viens de faire la modif sur 3 modules. Sa a l’air d’aller je vais continuer les tests au cas où. 
Merci :)

Envoyé de mon iPhone

**Comment by marvinroger** [comment]
J'ai mis beaucoup de temps à répondre aussi, pas de soucis. 😉

**Comment by marvinroger** [comment]
Tu peux rouvrir l'issue si c'est encore un problème.

**Comment by marmoul70** [comment]
Ok pas de soucis pour le moment sa a l’air bon je vais migrer les 7 autres et je te ferais un feed-back si besoin. 
Encore merci et bravo pour ton code il est au top!!!

Envoyé de mon iPhone

**Comment by marvinroger** [comment]
@marmoul70 merci à toi.
Tu l'utilises au quotidien ? A part ce souci quand le niveau est à 100%, tu n'as pas rencontré d'autres soucis ? C'est stable ?

Je te demande ça parce que je vais sûrement sortir la librairie de l'état de bêta.

**Comment by marmoul70** [comment]
Oui tout les jours avec des modules electrodragon double relay. J’ai actuellement 8 modules en place et sa fonctionne niquel avec mqtt et Jeedom depuis le mois de mars. 
A part le pb de 100% qui semble être réglé sur 3 volets j’ai rien remarqué d’autre. 
A mon avis c’est stable :)

Encore bravo c’est au top 

Envoyé de mon iPhone
