### ISSUE TITLE
restore state does not restore up and downCourseTime

### ISSUE THREAD

**Issue by mosseb** [marvinroger/arduino-shutters#18]
Hi.
We started using your library to deal with our own non smart shutters.
We're doing a good job so far, but we're stuck when we want to persist course times, and let them be settable through homie properties.
We think they should be restored by a call of restoreState because they are part of a ShuttersInternal::StoredState.
Unfortunately, when looking at the content of restoreState method :
https://github.com/marvinroger/arduino-shutters/blob/c761a680c9bcedc29b10da1f1605a5c6e23d42fa/src/Shutters.cpp#L78
Only the level is restored, but not the course times.
@marvinroger : Is it a bug ?

**Comment by marvinroger** [comment]
Thanks @mosseb 😉
