### ISSUE TITLE
Can't get exemple sketch to work

### ISSUE THREAD

**Issue by SebDominguez-zz** [marvinroger/arduino-shutters#23]
I may be doing something wrong but I really don't know what

![kapture 2018-11-30 at 16 58 47](https://user-images.githubusercontent.com/4247648/49300445-89f27080-f4c2-11e8-954a-a49eff925d44.gif)

Edit: Activating the debug mode throw me this message "Stored state is invalid".

I tried to call ```shutters.reset();``` but then this happened...

![kapture 2018-12-01 at 10 27 27](https://user-images.githubusercontent.com/4247648/49326527-c4581e00-f553-11e8-8bf2-30f4fa774415.gif)

Edit2: Ok now it seems to work. I just edited ```upCourseTime = 30 * 1000;``` to ```upCourseTime = 30000;```

**Comment by marvinroger** [comment]
Alright, thanks for the input. Is it fixed for you, then?

**Comment by SebDominguez-zz** [comment]
All seems to work fine now !
A little rectification on my last post: the bug was in the  `45 * 1000` part.
Since the compiler seems to keep the result in a short (and 45000 is > to 32767), I was ending trying to put in eeprom a negative number.
So just writing the cours time in ms or just casting them do the trick.

But I still get gibberish on the serial port when I try to use `shutters &reset();`

I may use it wrong ?
