### ISSUE TITLE
Exemple

### ISSUE THREAD

**Issue by pioueo** [marvinroger/arduino-shutters#3]
Bonjour,

Je me permets de m'exprimer en Français car j'ai vu que vous étiez Parisien.

Votre code sur les volets roulants semble super mais malgré l'exemple donné, je n'arrive pas à le faire fonctionner (mon niveau en programmation est proche de 0).
Serait-il possible que vous publiiez un exemple simple avec un ou deux volets en mettant en lumière les fonctions créées dans votre code?

Cordialement.

**Comment by marvinroger** [comment]
Effectivement, le code était beugué. La version 2.0.0 que je viens de mettre en ligne devrait corriger tous ces soucis. De plus, le code est non-bloquant. 😉
