### ISSUE TITLE
controle volet local

### ISSUE THREAD

**Issue by acornec** [marvinroger/arduino-shutters#6]
Bonjour
Je suis tombé sur votre librairie et j'ai réussi a le faire fonctionner avec la fonction shutters.setLevel(niv);
Par contre, est il possible également de faire évoluer la position du volet quand on actionne un relais directement 
En fait je controle aussi les volets en local depuis  un bouton physique ? si entrée = 1, relais = 1 et dans ce cas je voudrais que la position du volet évolue
Si possible, quelle fonction appeler ?
Si non, possible de faire évoluer dans ce sens ?
Je précise que je suis autodidacte en code et que mon niveau est plutot bas ;)
Merci d'avance

**Comment by marvinroger** [comment]
Bonjour,

Non, ce n'est pas possible, la librairie doit être la seule entité à contrôler l'état des relais, sinon elle ne fonctionnera plus correctement.

En revanche, lorsque vous appuyez sur le bouton physique, vous pouvez définir le `setlevel` sur 0 ou 100 selon que vous vouliez monter ou descendre. Lorsque vous relâchez le bouton, il suffit d'appeler `stop`.  Vous devriez obtenir le comportement que vous recherchez.

**Comment by acornec** [comment]
Parfait ca fonctionne, j'aurais du y penser 
Merci ;)
