### ISSUE TITLE
V3 redesign

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/arduino-shutters#7]
* Different instances of Shutters should be able to share the same callbacks
  * First parameter of the callbacks must be a pointer to the current Shutters instance
* Course time and calibration ratio must be settable after the Shutters instantiation
* New Shutters constructor would be:

```c++
Shutters(void (*upCallback)(Shutters* shutters), void (*downCallback)(Shutters* shutters), void (*haltCallback)(Shutters* shutters), uint8_t (*getStateCallback)(Shutters* shutters), void (*setStateCallback)(Shutters* shutters, uint8_t state));

// new methods

void .setCourseTime(uint32_t courseTime);
void .setCalibrationRatio(uint8_t calibrationLevel); // default value = 0.1
void .onLevelReached(void (*onLevelReachedCallback)(Shutters* shutters, uint8_t level));
```

`setCourseTime` must be called before the `begin`, otherwise `begin` would not do anything.
The course time would be stored in the state. We need 7 bits to store the level of the shutters, and the course time can be 32 bits. So let's put a new state that would be an `uint32_t`.

The schema would be this:

* 25 first bits: the course time. This allows 33,554,432ms, which is basically about 59 minutes, so this is enough. The `0` value means unset.
* 7 remaining bits: The known level. We'll say a clean state would be 0, so let's actually offset the state by 28. Therefore, 28 would be 0% and 128 would be 100%.

This allows the course time to be defined at runtime. If we call `setCourseTime` when the saved course time is 0 or a different one, the shutters would consider the state is unknown. If the value is the same as the saved one, then we consider the state is known.

Also, another change, the `reset` method should not "disable" the library. It should instead put itself in "pre-begin" phase.

**Comment by Czara** [comment]
Hi, 
J'attends justement cette possibilité : void .setCourseTime(uint32_t courseTime); 
Merci

**Comment by marvinroger** [comment]
@Czara released as beta: https://github.com/marvinroger/arduino-shutters/releases/tag/v3.0.0-beta.1

😃
