### ISSUE TITLE
EEPROMWrite

### ISSUE THREAD

**Issue by ludodoucet** [marvinroger/arduino-shutters#9]
I use an arduino mega, after a power cut, the shutters go up, while they were positioned at 50.
I tried to understand how data was stored by callback without success.
If I had the address on the eeprom, I could check what happens. From 0 to 9 the value remains at 255.
Can you help me?

**Comment by marvinroger** [comment]
See https://github.com/marvinroger/homie-esp8266/blob/develop/examples/SonoffDualShutters/SonoffDualShutters.ino

You don't *have* the address, you store it wherever you want.

**Comment by ludodoucet** [comment]
Ok c'est réglé 1000 merci
